version: '3.8'

services:
    postgres:
        image: postgres:13
        restart: always
        container_name: db_url
        env_file:
            - '.env'
        ports:
            - 5433:5432
        volumes:
            - pgdata:/var/lib/postgresql/data
    app:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - '.env'
        # command: sh -c "npm run  start:dev"
        depends_on:
            - postgres
        container_name: app_url
        volumes:
            - '~/.bash_history:/.bash_history'
            - './:/usr/src/app:cached'
        ports:
            - 3000:3000

volumes:
    pgdata:
    redisdata:
